### ISSUE TITLE
I couldn't file dataGrid.js and dataGrid.css files

### ISSUE THREAD

**Issue by adarshkhatri** [HPUinternet/zf2-doctrine-datagrid#12]
Not sure if this is issue?

I couldn't file dataGrid.js and dataGrid.css files

    /css/Admin/DataGrid/Dist/dataGrid.css
    js/Admin/DataGrid/Dist/dataGrid.js

Where are they?

**Comment by dymen1** [comment]
Hi,

those are compiled files, generate by a assetmanager.
in the assetmanager.config.php:
collections' => array(
    'js/Admin/DataGrid/Dist/dataGrid.js' => array(
        '/js/Admin/DataGrid/datagrid.js',
    ),
    'css/Admin/DataGrid/Dist/dataGrid.css' => array(
        '/css/Admin/DataGrid/style.css',
    ),
),

I highly recommend using a assetmanager to compile your assets, but if you want to don't want to use one you can do the following:
copy the files in de modules public/js and public/css folder to your applications public folder.
'js/Admin/DataGrid/datagrid.js' => 'js/Admin/DataGrid/Dist/dataGrid.js' and
'css/Admin/DataGrid/style.css' => 'css/Admin/DataGrid/Dist/dataGrid.css'

I hope this is sufficient to help you.
