### ISSUE TITLE
Filtering not working for me

### ISSUE THREAD

**Issue by adarshkhatri** [HPUinternet/zf2-doctrine-datagrid#13]
Awesome module. Thank you for that.

It might not be bug.

I am having trouble getting it work with filter.

I have added this

    'filters' => array(
            'Wms\Admin\User\Filter\PersonalEntitiesFilter' => 'Wms\Admin\User\Filter\PersonalEntitiesFilterParams'
        ),

in my `module.config.php` but it doesn't works.

Any more info how can I get it work? And is there platform to ask qst regarding this module instead of creating issue ticket (which is not issue) here?

**Comment by dymen1** [comment]
Hi, awesome that you like the module.

Could you specify what doesn't work? 
Do you get an error?
And do you have the class 'Wms\Admin\User\Filter\PersonalEntitiesFilter' loaded in your project?

**Comment by adarshkhatri** [comment]
Filter doesn't happens with my data. I just get all data rendered as default.

Yes i have the class loaded in project and can confirm that rendering is working.

Only the filtering is the problem.

Also, is there a way to export filtered/search data in csv format?

**Comment by dymen1** [comment]
Do your entities use the createdBy field to indicate who created the field?

And currently there is no feature that exports to csv, but we welcome pull requests!

**Comment by adarshkhatri** [comment]
my entities uses "client", which is foreign key to all users that are logged in.

**Comment by dymen1** [comment]
Did you change the field the filter filters on to client instead of
createdBy?

2016-06-22 9:04 GMT+02:00 Adarsh Khatri <notifications@github.com>:

**Comment by adarshkhatri** [comment]
yes, infact I was debugging, and did die() or exit() in filter class, but they never called. 

I have placed this code in my module's module.config.php

```
'filters' => array(
        'Wms\Admin\User\Filter\PersonalEntitiesFilter' => 'Wms\Admin\User\Filter\PersonalEntitiesFilterParams'
    ),
```

**Comment by dymen1** [comment]
Can you post everything under the 'wms-datagrid' config key?

**Comment by adarshkhatri** [comment]
sorry I don't follow.

**Comment by dymen1** [comment]
Can you post the context in which you placed the code?

It should resemble something like this:
```
'wms-datagrid' => array(
    'Application\Controller\Index' => array (
        'entityName' => 'Wms\Admin\MediaManager\Entity\MediaItem',
        'defaultColumns' => array(
            'id', 'title', 'caption', 'originalFile.mimetype', 'originalFile.size', 'thumbnailFile.imagepath'
        ),
        'filters' => array(
            'Wms\Admin\User\Filter\PersonalEntitiesFilter' => 'Wms\Admin\User\Filter\PersonalEntitiesFilterParams'
        ),
    ),
);
```

**Comment by adarshkhatri** [comment]
Here,

```
return array(
    'controllers' => array(
        'invokables' => array(
            'Student\Controller\Index' => 'Student\Controller\IndexController',
        ),
    ),
        'wms-datagrid' => array(
            'Student\Controller\Index' => array(
                'entityName' => 'Student\Entity\Student',
                'defaultColumns' => array('client.clientcode', 'profilePicUrl', 'studentcode', 'lastname', 'firstname', 'gender', 'dob', 'phone', 'mobile', 'email', 'join_fee_paid', 'occupation', 'educationlevel', 'schoolname', 'preferrerd_days', 'status', 'action'),
            ),
            'prohibitedColumns' => array (
                'id', //this is also not hiding
            ),
            'filters' => array(
                'Wms\Admin\User\Filter\PersonalEntitiesFilter' => 'Wms\Admin\User\Filter\PersonalEntitiesFilterParams'
            ),
        ),
       
    'router' => array(
        'routes' => array(
            'student' => array(
                'type' => 'Segment',
                'options' => array(
```

**Comment by adarshkhatri** [comment]
Right, thanks for quick reply.

I think I am not loading `'Wms\Admin\User\Filter\PersonalEntitiesFilter'`

How do I load it? I thought when this module installed, it would load automatically.

    Fatal error: Class 'Wms\Admin\User\Filter\PersonalEntitiesFilterParams' not found in /Applications/XAMPP/xamppfiles/htdocs/skeleton/vendor/hpu/zf2-doctrine-datagrid/src/Factory/QueryFilterHelperFactory.php on line 27

**Comment by dymen1** [comment]
The class itself isn't part of the module, the code however is included in the [documentation](https://github.com/HPUinternet/zf2-doctrine-datagrid/blob/master/docs/2.3.%20Filters.md).
In other words: you need to add it yourself.

A bonus result of doing this is that you can use your own namespace and class name!

**Comment by adarshkhatri** [comment]
Thanks, finally I am able to load filters, although this condition is never met in my case:

    if($targetEntity->name == $this->cleanParameter($this->getParameter('entityName'))
           && $targetEntity->hasField('id') 
           && $this->getParameter('clientId')
          ){
            return $targetTableAlias . '.client = ' . $this->getParameter('clientId');
        }

I am filtering "Student" entity. And my student entity has foreign key named "client" from "User" entity.

Here, 

     echo $targetEntity->name; // 'User\Entity\User'
     echo $this->cleanParameter($this->getParameter('entityName')); // 'Student\Entity\Student'

What am I doing wrong?

**Comment by adarshkhatri** [comment]
if($targetEntity->name === $this->cleanParameter($this->getParameter('entityName'))

did worked.
