### ISSUE TITLE
Installation command doens't work

### ISSUE THREAD

**Issue by dymen1** [HPUinternet/zf2-doctrine-datagrid#8]
`composer require hpu/zf2-doctrine-datagrid` 
"hpu/zf2-doctrine-datagrid" isn't on packagist
"hpu/wms-admin-datagrid" is

**Comment by nstapelbroek** [comment]
About that, maybe @rsplithof  could give his opinion on the preferred package name? I would rather refactor `hpu/wms-admin-datagrid` to `hpu/zf2-doctrine-datagrid` since its more consistent in naming than the other way around.

**Comment by rsplithof** [comment]
I'm okay with the packagename to be `hpu/zf2-doctrine-datagrid`.
@nstapelbroek can you add me to the hpu/ prefix on packagist? This way i can publish packages under the name of HPU. Thnx in advance

**Comment by nstapelbroek** [comment]
Could you guys pass me your packagist.org username? Then I can add you as a maintainer of the package. AFAIK there is no protected `hpu/` vendor namespace? If you are having trouble publishing a package with the hpu vendor name, I will delete the package allowing you to create some sort of collaboration account which can hold all the hpu packages.

**Comment by rsplithof** [comment]
Done :)
